package myway.myapplication.network.model.tasks

import com.google.gson.annotations.SerializedName

data class TaskPages (
	@SerializedName("total") val total : Int,
	@SerializedName("rows") val task_pages : List<TaskPages>,
	val success: Boolean,

	@SerializedName("id") val id : Int,
	@SerializedName("name_ru") val name_ru : String,
	@SerializedName("name_uk") val name_uk : String,
	@SerializedName("name_uz") val name_uz : String,
	@SerializedName("name") val name : String,
	@SerializedName("parent_id") val parent_id : String,
	@SerializedName("description") val description : String,
	@SerializedName("task_statuses_id") val task_statuses_id : Int,
	@SerializedName("task_types_id") val task_types_id : Int,
	@SerializedName("task_priorities_id") val task_priorities_id : Int,
	@SerializedName("task_platforms_id") val task_platforms_id : Int,
	@SerializedName("curr_executor_id") val curr_executor_id : String,
	@SerializedName("expired_date") val expired_date : String,
	@SerializedName("created_date") val created_date : Int,
	@SerializedName("created_users_id") val created_users_id : Int,
	@SerializedName("date_end") val date_end : String,
	@SerializedName("ordering") val ordering : String,
	@SerializedName("is_editable") val is_editable : Int,
	@SerializedName("task_ranks_id") val task_ranks_id : String,
	@SerializedName("task_ranks_name") val task_ranks_name : String,
	@SerializedName("task_ranks_color") val task_ranks_color : String,
	@SerializedName("task_ranks_icon") val task_ranks_icon : String,
	@SerializedName("task_statuses_ids") val task_statuses_ids : String,
	@SerializedName("task_code") val task_code : String,
	@SerializedName("projects_id") val projects_id : Int,
	@SerializedName("projects_name") val projects_name : String,
	@SerializedName("projects_short_name") val projects_short_name : String,
	@SerializedName("projects_color") val projects_color : String,
	@SerializedName("parent_name") val parent_name : String,
	@SerializedName("task_statuses_name") val task_statuses_name : String,
	@SerializedName("task_statuses_icon") val task_statuses_icon : String,
	@SerializedName("task_statuses_color") val task_statuses_color : String,
	@SerializedName("task_types_name") val task_types_name : String,
	@SerializedName("task_types_icon") val task_types_icon : String,
	@SerializedName("task_types_color") val task_types_color : String,
	@SerializedName("task_priorities_name") val task_priorities_name : String,
	@SerializedName("task_priorities_icon") val task_priorities_icon : String,
	@SerializedName("task_priorities_color") val task_priorities_color : String,
	@SerializedName("task_platforms_name") val task_platforms_name : String,
	@SerializedName("task_platforms_icon") val task_platforms_icon : String,
	@SerializedName("task_platforms_color") val task_platforms_color : String,
	@SerializedName("curr_executor_name") val curr_executor_name : String,
	@SerializedName("curr_executor_resources_id") val curr_executor_resources_id : String,
	@SerializedName("created_users_name") val created_users_name : String,
	@SerializedName("created_user_resources_id") val created_user_resources_id : Int,
	@SerializedName("is_late") val is_late : Int,
	@SerializedName("left_days") val left_days : String,
	@SerializedName("hard_index") val hard_index : Int,
	@SerializedName("undone_tasks") val undone_tasks : Int,
	@SerializedName("status_description") val status_description : String,
	@SerializedName("parent_task_code") val parent_task_code : String,
	@SerializedName("parent_task_name") val parent_task_name : String,
	@SerializedName("task_status_date") val task_status_date : Int,
	@SerializedName("start_date") val start_date : String,
	@SerializedName("active_days") val active_days : String,
	@SerializedName("is_set_executor") val is_set_executor : String,
	@SerializedName("is_done_task") val is_done_task : String,
	@SerializedName("project_categories_name") val project_categories_name : String,
	@SerializedName("project_categories_icon") val project_categories_icon : String,
	@SerializedName("project_categories_color") val project_categories_color : String,
	@SerializedName("file_ids") val file_ids : String

)